# Generated by Django 2.1.3 on 2018-12-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicCronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.PositiveIntegerField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolved_pattern', models.CharField(blank=True, editable=False, max_length=255)),
                ('last_resolved', models.DateTimeField(blank=True, editable=False, null=True)),
                ('instance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Dynamic Cron Job',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcron.DynamicCronJob')),
            ],
            options={
                'verbose_name': 'Log',
            },
        ),
        migrations.CreateModel(
            name='ScheduledManagementCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('cron_schedule', models.CharField(blank=True, default='* * * * *', max_length=255)),
                ('management_command', models.CharField(default='test', max_length=255)),
            ],
            options={
                'verbose_name': 'Scheduled Management Command',
            },
        ),
        migrations.CreateModel(
            name='ScheduledShellCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('cron_schedule', models.CharField(blank=True, default='* * * * *', max_length=255)),
                ('shell_command', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Scheduled Shell Command',
            },
        ),
    ]
